	<?php
    $this->load->view('mapControls');
		$this->load->view('map');
    $this->load->view('routeHeader');
    $this->load->view('routeDetail');
    $this->load->view('routeFooter');
    $this->load->view('evaluaciones');
    $this->load->view('charts');
    $this->load->view('thanks');
	?>
